`-` R 패키지

> CRAN에서 pdf를 다운받으면 그 설명이 가장 상세하다.

In [ ]:
install.packages("remotes")
library(remotes)

In [ ]:
install_github("URL", force = TRUE)  ## 깃허브에 있는 것을 직접 인스톨하는 것

In [5]:
library(MASS)

In [4]:
install.packages("MASS")

Updating HTML index of packages in '.Library'

Making 'packages.html' ...
 done

In [6]:
ls(packages:MASS)

Warning message in ls(packages:MASS):
“‘packages:MASS’ converted to character string”

ERROR: Error in as.environment(pos): no item called "packages:MASS" on the search list

`-` 함수

In [7]:
me = function(a) {
    rs = sum(a) / length(a)
    return(rs)
}

me(1:10)

[1] 5.5

> 입-출력이 있는 함수를 기본으로 한다. 함수 내애서의 연산은 로컬이다.

In [13]:
v_1 <- function() {
    v <<- 1
}

In [16]:
v = 0
v_1()
v

[1] 1

`-` `dplyr`

In [17]:
library(dplyr)

Attaching package: ‘dplyr’


The following object is masked from ‘package:MASS’:

    select


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

In [18]:
str(starwars)  ## structure

tibble [87 × 14] (S3: tbl_df/tbl/data.frame)
 $ name      : chr [1:87] "Luke Skywalker" "C-3PO" "R2-D2" "Darth Vader" ...
 $ height    : int [1:87] 172 167 96 202 150 178 165 97 183 182 ...
 $ mass      : num [1:87] 77 75 32 136 49 120 75 32 84 77 ...
 $ hair_color: chr [1:87] "blond" NA NA "none" ...
 $ skin_color: chr [1:87] "fair" "gold" "white, blue" "white" ...
 $ eye_color : chr [1:87] "blue" "yellow" "red" "yellow" ...
 $ birth_year: num [1:87] 19 112 33 41.9 19 52 47 NA 24 57 ...
 $ sex       : chr [1:87] "male" "none" "none" "male" ...
 $ gender    : chr [1:87] "masculine" "masculine" "masculine" "masculine" ...
 $ homeworld : chr [1:87] "Tatooine" "Tatooine" "Naboo" "Tatooine" ...
 $ species   : chr [1:87] "Human" "Droid" "Droid" "Human" ...
 $ films     :List of 87
  ..$ : chr [1:5] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "Revenge of the Sith" ...
  ..$ : chr [1:6] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "The Phantom Menace" ...
  ..$ : chr [1:7] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "The Phantom Menace" ...
  ..$ : chr [1:4] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "Revenge of the Sith"
  ..$ : chr [1:5] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "Revenge of the Sith" ...
  ..$ : chr [1:3] "A New Hope" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:3] "A New Hope" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "A New Hope"
  ..$ : chr "A New Hope"
  ..$ : chr [1:6] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "The Phantom Menace" ...
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "A New Hope" "Revenge of the Sith"
  ..$ : chr [1:5] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "Revenge of the Sith" ...
  ..$ : chr [1:4] "A New Hope" "The Empire Strikes Back" "Return of the Jedi" "The Force Awakens"
  ..$ : chr "A New Hope"
  ..$ : chr [1:3] "A New Hope" "Return of the Jedi" "The Phantom Menace"
  ..$ : chr [1:3] "A New Hope" "The Empire Strikes Back" "Return of the Jedi"
  ..$ : chr "A New Hope"
  ..$ : chr [1:5] "The Empire Strikes Back" "Return of the Jedi" "The Phantom Menace" "Attack of the Clones" ...
  ..$ : chr [1:5] "The Empire Strikes Back" "Return of the Jedi" "The Phantom Menace" "Attack of the Clones" ...
  ..$ : chr [1:3] "The Empire Strikes Back" "Return of the Jedi" "Attack of the Clones"
  ..$ : chr "The Empire Strikes Back"
  ..$ : chr "The Empire Strikes Back"
  ..$ : chr [1:2] "The Empire Strikes Back" "Return of the Jedi"
  ..$ : chr "The Empire Strikes Back"
  ..$ : chr [1:2] "Return of the Jedi" "The Force Awakens"
  ..$ : chr "Return of the Jedi"
  ..$ : chr "Return of the Jedi"
  ..$ : chr "Return of the Jedi"
  ..$ : chr "Return of the Jedi"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "The Phantom Menace" "Attack of the Clones"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:2] "The Phantom Menace" "Attack of the Clones"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:2] "The Phantom Menace" "Attack of the Clones"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "Return of the Jedi"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "The Phantom Menace" "Revenge of the Sith"
  ..$ : chr [1:2] "The Phantom Menace" "Revenge of the Sith"
  ..$ : chr [1:2] "The Phantom Menace" "Revenge of the Sith"
  ..$ : chr "The Phantom Menace"
  ..$ : chr [1:3] "The Phantom Menace" "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "The Phantom Menace" "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "Attack of the Clones"
  ..$ : chr "Attack of the Clones"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "Revenge of the Sith"
  ..$ : chr "Revenge of the Sith"
  ..$ : chr [1:2] "A New Hope" "Revenge of the Sith"
  ..$ : chr [1:2] "Attack of the Clones" "Revenge of the Sith"
  ..$ : chr "Revenge of the Sith"
  ..$ : chr "The Force Awakens"
  ..$ : chr "The Force Awakens"
  ..$ : chr "The Force Awakens"
  ..$ : chr "The Force Awakens"
  ..$ : chr "The Force Awakens"
 $ vehicles  :List of 87
  ..$ : chr [1:2] "Snowspeeder" "Imperial Speeder Bike"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Imperial Speeder Bike"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Tribubble bongo"
  ..$ : chr [1:2] "Zephyr-G swoop bike" "XJ-6 airspeeder"
  ..$ : chr(0)
  ..$ : chr "AT-ST"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Snowspeeder"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Tribubble bongo"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Sith speeder"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Flitknot speeder"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Koro-2 Exodrive airspeeder"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Tsmeu-6 personal wheel bike"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
 $ starships :List of 87
  ..$ : chr [1:2] "X-wing" "Imperial shuttle"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "TIE Advanced x1"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "X-wing"
  ..$ : chr [1:5] "Jedi starfighter" "Trade Federation cruiser" "Naboo star skiff" "Jedi Interceptor" ...
  ..$ : chr [1:3] "Naboo fighter" "Trade Federation cruiser" "Jedi Interceptor"
  ..$ : chr(0)
  ..$ : chr [1:2] "Millennium Falcon" "Imperial shuttle"
  ..$ : chr [1:2] "Millennium Falcon" "Imperial shuttle"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "X-wing"
  ..$ : chr "X-wing"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Slave 1"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Millennium Falcon"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "A-wing"
  ..$ : chr(0)
  ..$ : chr "Millennium Falcon"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr [1:3] "Naboo fighter" "H-type Nubian yacht" "Naboo star skiff"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Naboo Royal Starship"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Scimitar"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Jedi starfighter"
  ..$ : chr(0)
  ..$ : chr "Naboo fighter"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "Belbullab-22 starfighter"
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr(0)
  ..$ : chr "X-wing"
  ..$ : chr(0)
  ..$ : chr(0)

`-` select

In [20]:
starwars |> filter(species == "Droid")

  name   height mass hair_color skin_color  eye_color birth_year sex  gender
1 C-3PO  167     75  NA         gold        yellow    112        none masculine
2 R2-D2   96     32  NA         white, blue red        33        none masculine
3 R5-D4   97     32  NA         white, red  red        NA        none masculine
4 IG-88  200    140  none       metal       red        15        none masculine
5 R4-P17  96     NA  none       silver, red red, blue  NA        none feminine
6 BB8     NA     NA  none       none        black      NA        none masculine
  homeworld species
1 Tatooine  Droid
2 Naboo     Droid
3 Tatooine  Droid
4 NA        Droid
5 NA        Droid
6 NA        Droid
  films
1 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
2 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith    , The Force Awakens
3 A New Hope
4 The Empire Strikes Back
5 Attack of the Clones, Revenge of the Sith
6 The Force Awakens
  vehicles starships
1
2
3
4
5
6

In [19]:
a = starwars %>% filter(species == "Droid")
a

  name   height mass hair_color skin_color  eye_color birth_year sex  gender
1 C-3PO  167     75  NA         gold        yellow    112        none masculine
2 R2-D2   96     32  NA         white, blue red        33        none masculine
3 R5-D4   97     32  NA         white, red  red        NA        none masculine
4 IG-88  200    140  none       metal       red        15        none masculine
5 R4-P17  96     NA  none       silver, red red, blue  NA        none feminine
6 BB8     NA     NA  none       none        black      NA        none masculine
  homeworld species
1 Tatooine  Droid
2 Naboo     Droid
3 Tatooine  Droid
4 NA        Droid
5 NA        Droid
6 NA        Droid
  films
1 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
2 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith    , The Force Awakens
3 A New Hope
4 The Empire Strikes Back
5 Attack of the Clones, Revenge of the Sith
6 The Force Awakens
  vehicles starships
1
2
3
4
5
6

`-` project

In [22]:
b = select(starwars, name, ends_with("color"))  ## "color"로 끝나는 변수 명을 선택함

In [24]:
starwars %>% select(name, ends_with("color"))

   name                  hair_color    skin_color          eye_color
1  Luke Skywalker        blond         fair                blue
2  C-3PO                 NA            gold                yellow
3  R2-D2                 NA            white, blue         red
4  Darth Vader           none          white               yellow
5  Leia Organa           brown         light               brown
6  Owen Lars             brown, grey   light               blue
7  Beru Whitesun Lars    brown         light               blue
8  R5-D4                 NA            white, red          red
9  Biggs Darklighter     black         light               brown
10 Obi-Wan Kenobi        auburn, white fair                blue-gray
11 Anakin Skywalker      blond         fair                blue
12 Wilhuff Tarkin        auburn, grey  fair                blue
13 Chewbacca             brown         unknown             blue
14 Han Solo              brown         fair                brown
15 Greedo                NA            green               black
16 Jabba Desilijic Tiure NA            green-tan, brown    orange
17 Wedge Antilles        brown         fair                hazel
18 Jek Tono Porkins      brown         fair                blue
19 Yoda                  white         green               brown
20 Palpatine             grey          pale                yellow
21 Boba Fett             black         fair                brown
22 IG-88                 none          metal               red
23 Bossk                 none          green               red
24 Lando Calrissian      black         dark                brown
25 Lobot                 none          light               blue
26 Ackbar                none          brown mottle        orange
27 Mon Mothma            auburn        fair                blue
28 Arvel Crynyd          brown         fair                brown
29 Wicket Systri Warrick brown         brown               brown
30 Nien Nunb             none          grey                black
⋮  ⋮                     ⋮             ⋮                   ⋮
58 Mas Amedda            none          blue                blue
59 Gregar Typho          black         dark                brown
60 Cordé                 brown         light               brown
61 Cliegg Lars           brown         fair                blue
62 Poggle the Lesser     none          green               yellow
63 Luminara Unduli       black         yellow              blue
64 Barriss Offee         black         yellow              blue
65 Dormé                 brown         light               brown
66 Dooku                 white         fair                brown
67 Bail Prestor Organa   black         tan                 brown
68 Jango Fett            black         tan                 brown
69 Zam Wesell            blonde        fair, green, yellow yellow
70 Dexter Jettster       none          brown               yellow
71 Lama Su               none          grey                black
72 Taun We               none          grey                black
73 Jocasta Nu            white         fair                blue
74 R4-P17                none          silver, red         red, blue
75 Wat Tambor            none          green, grey         unknown
76 San Hill              none          grey                gold
77 Shaak Ti              none          red, blue, white    black
78 Grievous              none          brown, white        green, yellow
79 Tarfful               brown         brown               blue
80 Raymus Antilles       brown         light               brown
81 Sly Moore             none          pale                white
82 Tion Medon            none          grey                black
83 Finn                  black         dark                dark
84 Rey                   brown         light               hazel
85 Poe Dameron           brown         light               brown
86 BB8                   none          none                black
87 Captain Phasma        none          none                unknown

`-` mutation : 변이 $\to$ `df.assign(lambda _df : _df.height.apply(lambda x : x**2))`

In [27]:
c = starwars %>% mutate(bmi = mass / (height / 100)^2) %>% select(name, mass, bmi)  ## 두 번 연산
c

   name                  mass   bmi
1  Luke Skywalker          77.0  26.02758
2  C-3PO                   75.0  26.89232
3  R2-D2                   32.0  34.72222
4  Darth Vader            136.0  33.33007
5  Leia Organa             49.0  21.77778
6  Owen Lars              120.0  37.87401
7  Beru Whitesun Lars      75.0  27.54821
8  R5-D4                   32.0  34.00999
9  Biggs Darklighter       84.0  25.08286
10 Obi-Wan Kenobi          77.0  23.24598
11 Anakin Skywalker        84.0  23.76641
12 Wilhuff Tarkin            NA        NA
13 Chewbacca              112.0  21.54509
14 Han Solo                80.0  24.69136
15 Greedo                  74.0  24.72518
16 Jabba Desilijic Tiure 1358.0 443.42857
17 Wedge Antilles          77.0  26.64360
18 Jek Tono Porkins       110.0  33.95062
19 Yoda                    17.0  39.02663
20 Palpatine               75.0  25.95156
21 Boba Fett               78.2  23.35095
22 IG-88                  140.0  35.00000
23 Bossk                  113.0  31.30194
24 Lando Calrissian        79.0  25.21625
25 Lobot                   79.0  25.79592
26 Ackbar                  83.0  25.61728
27 Mon Mothma                NA        NA
28 Arvel Crynyd              NA        NA
29 Wicket Systri Warrick   20.0  25.82645
30 Nien Nunb               68.0  26.56250
⋮  ⋮                     ⋮      ⋮
58 Mas Amedda               NA        NA
59 Gregar Typho           85.0  24.83565
60 Cordé                    NA        NA
61 Cliegg Lars              NA        NA
62 Poggle the Lesser      80.0  23.88844
63 Luminara Unduli        56.2  19.44637
64 Barriss Offee          50.0  18.14487
65 Dormé                    NA        NA
66 Dooku                  80.0  21.47709
67 Bail Prestor Organa      NA        NA
68 Jango Fett             79.0  23.58984
69 Zam Wesell             55.0  19.48696
70 Dexter Jettster       102.0  26.01775
71 Lama Su                88.0  16.78076
72 Taun We                  NA        NA
73 Jocasta Nu               NA        NA
74 R4-P17                   NA        NA
75 Wat Tambor             48.0  12.88625
76 San Hill                 NA        NA
77 Shaak Ti               57.0  17.99015
78 Grievous              159.0  34.07922
79 Tarfful               136.0  24.83746
80 Raymus Antilles        79.0  22.35174
81 Sly Moore              48.0  15.14960
82 Tion Medon             80.0  18.85192
83 Finn                     NA        NA
84 Rey                      NA        NA
85 Poe Dameron              NA        NA
86 BB8                      NA        NA
87 Captain Phasma           NA        NA

`-` sorting : sort_values()

In [31]:
d = starwars %>% arrange(desc(mass))  ## descending
starwars %>% arrange(mass)  ## 오름차순

   name                  height mass hair_color    skin_color
1  Ratts Tyerel           79    15.0 none          grey, blue
2  Yoda                   66    17.0 white         green
3  Wicket Systri Warrick  88    20.0 brown         brown
4  R2-D2                  96    32.0 NA            white, blue
5  R5-D4                  97    32.0 NA            white, red
6  Sebulba               112    40.0 none          grey, red
7  Padmé Amidala         185    45.0 brown         light
8  Dud Bolt               94    45.0 none          blue, grey
9  Wat Tambor            193    48.0 none          green, grey
10 Sly Moore             178    48.0 none          pale
11 Leia Organa           150    49.0 brown         light
12 Adi Gallia            184    50.0 none          dark
13 Barriss Offee         166    50.0 black         yellow
14 Ayla Secura           178    55.0 none          blue
15 Zam Wesell            168    55.0 blonde        fair, green, yellow
16 Luminara Unduli       170    56.2 black         yellow
17 Shaak Ti              178    57.0 none          red, blue, white
18 Ben Quadinaros        163    65.0 none          grey, green, yellow
19 Jar Jar Binks         196    66.0 none          orange
20 Nien Nunb             160    68.0 none          grey
21 Greedo                173    74.0 NA            green
22 C-3PO                 167    75.0 NA            gold
23 Beru Whitesun Lars    165    75.0 brown         light
24 Palpatine             170    75.0 grey          pale
25 Luke Skywalker        172    77.0 blond         fair
26 Obi-Wan Kenobi        182    77.0 auburn, white fair
27 Wedge Antilles        170    77.0 brown         fair
28 Boba Fett             183    78.2 black         fair
29 Lando Calrissian      177    79.0 black         dark
30 Lobot                 175    79.0 none          light
⋮  ⋮                     ⋮      ⋮    ⋮             ⋮
58 Grievous              216     159 none          brown, white
59 Jabba Desilijic Tiure 175    1358 NA            green-tan, brown
60 Wilhuff Tarkin        180      NA auburn, grey  fair
61 Mon Mothma            150      NA auburn        fair
62 Arvel Crynyd           NA      NA brown         fair
63 Finis Valorum         170      NA blond         fair
64 Rugor Nass            206      NA none          green
65 Ric Olié              183      NA brown         fair
66 Watto                 137      NA black         blue, grey
67 Quarsh Panaka         183      NA black         dark
68 Shmi Skywalker        163      NA black         fair
69 Bib Fortuna           180      NA none          pale
70 Gasgano               122      NA none          white, blue
71 Eeth Koth             171      NA black         brown
72 Saesee Tiin           188      NA none          pale
73 Yarael Poof           264      NA none          white
74 Mas Amedda            196      NA none          blue
75 Cordé                 157      NA brown         light
76 Cliegg Lars           183      NA brown         fair
77 Dormé                 165      NA brown         light
78 Bail Prestor Organa   191      NA black         tan
79 Taun We               213      NA none          grey
80 Jocasta Nu            167      NA white         fair
81 R4-P17                 96      NA none          silver, red
82 San Hill              191      NA none          grey
83 Finn                   NA      NA black         dark
84 Rey                    NA      NA brown         light
85 Poe Dameron            NA      NA brown         light
86 BB8                    NA      NA none          none
87 Captain Phasma         NA      NA none          none
   eye_color     birth_year sex            gender    homeworld   species
1  unknown          NA      male           masculine Aleen Minor Aleena
2  brown         896.0      male           masculine NA          Yoda's species
3  brown           8.0      male           masculine Endor       Ewok
4  red            33.0      none           masculine Naboo       Droid
5  red              NA      none           masculine Tatooine    Droid
6  orange           NA      male           masculine Malastare   Dug
7  brown          46.0      female         feminine  Naboo       Human
8  yellow           NA      male           masculine Vulpter     Vulptereen
9  unknown          NA      male           masculine Skako       Skakoan
10 white            NA      NA             NA        Umbara      NA
11 brown          19.0      female         feminine  Alderaan    Human
12 blue             NA      female         feminine  Coruscant   Tholothian
13 blue           40.0      female         feminine  Mirial      Mirialan
14 hazel          48.0      female         feminine  Ryloth      Twi'lek
15 yellow           NA      female         feminine  Zolan       Clawdite
16 blue           58.0      female         feminine  Mirial      Mirialan
17 black            NA      female         feminine  Shili       Togruta
18 orange           NA      male           masculine Tund        Toong
19 orange         52.0      male           masculine Naboo       Gungan
20 black            NA      male           masculine Sullust     Sullustan
21 black          44.0      male           masculine Rodia       Rodian
22 yellow        112.0      none           masculine Tatooine    Droid
23 blue           47.0      female         feminine  Tatooine    Human
24 yellow         82.0      male           masculine Naboo       Human
25 blue           19.0      male           masculine Tatooine    Human
26 blue-gray      57.0      male           masculine Stewjon     Human
27 hazel          21.0      male           masculine Corellia    Human
28 brown          31.5      male           masculine Kamino      Human
29 brown          31.0      male           masculine Socorro     Human
30 blue           37.0      male           masculine Bespin      Human
⋮  ⋮             ⋮          ⋮              ⋮         ⋮           ⋮
58 green, yellow  NA        male           masculine Kalee       Kaleesh
59 orange        600        hermaphroditic masculine Nal Hutta   Hutt
60 blue           64        male           masculine Eriadu      Human
61 blue           48        female         feminine  Chandrila   Human
62 brown          NA        male           masculine NA          Human
63 blue           91        male           masculine Coruscant   Human
64 orange         NA        male           masculine Naboo       Gungan
65 blue           NA        male           masculine Naboo       Human
66 yellow         NA        male           masculine Toydaria    Toydarian
67 brown          62        male           masculine Naboo       Human
68 brown          72        female         feminine  Tatooine    Human
69 pink           NA        male           masculine Ryloth      Twi'lek
70 black          NA        male           masculine Troiken     Xexto
71 brown          NA        male           masculine Iridonia    Zabrak
72 orange         NA        male           masculine Iktotch     Iktotchi
73 yellow         NA        male           masculine Quermia     Quermian
74 blue           NA        male           masculine Champala    Chagrian
75 brown          NA        NA             NA        Naboo       NA
76 blue           82        male           masculine Tatooine    Human
77 brown          NA        female         feminine  Naboo       Human
78 brown          67        male           masculine Alderaan    Human
79 black          NA        female         feminine  Kamino      Kaminoan
80 blue           NA        female         feminine  Coruscant   Human
81 red, blue      NA        none           feminine  NA          Droid
82 gold           NA        male           masculine Muunilinst  Muun
83 dark           NA        male           masculine NA          Human
84 hazel          NA        female         feminine  NA          Human
85 brown          NA        male           masculine NA          Human
86 black          NA        none           masculine NA          Droid
87 unknown        NA        female         feminine  NA          Human
   films
1  The Phantom Menace
2  The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
3  Return of the Jedi
4  A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith    , The Force Awakens
5  A New Hope
6  The Phantom Menace
7  The Phantom Menace  , Attack of the Clones, Revenge of the Sith
8  The Phantom Menace
9  Attack of the Clones
10 Attack of the Clones, Revenge of the Sith
11 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith    , The Force Awakens
12 The Phantom Menace , Revenge of the Sith
13 Attack of the Clones
14 The Phantom Menace  , Attack of the Clones, Revenge of the Sith
15 Attack of the Clones
16 Attack of the Clones, Revenge of the Sith
17 Attack of the Clones, Revenge of the Sith
18 The Phantom Menace
19 The Phantom Menace  , Attack of the Clones
20 Return of the Jedi
21 A New Hope
22 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
23 A New Hope          , Attack of the Clones, Revenge of the Sith
24 The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
25 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith    , The Force Awakens
26 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
27 A New Hope             , The Empire Strikes Back, Return of the Jedi
28 The Empire Strikes Back, Return of the Jedi     , Attack of the Clones
29 The Empire Strikes Back, Return of the Jedi
30 The Empire Strikes Back
⋮  ⋮
58 Revenge of the Sith
59 A New Hope        , Return of the Jedi, The Phantom Menace
60 A New Hope         , Revenge of the Sith
61 Return of the Jedi
62 Return of the Jedi
63 The Phantom Menace
64 The Phantom Menace
65 The Phantom Menace
66 The Phantom Menace  , Attack of the Clones
67 The Phantom Menace
68 The Phantom Menace  , Attack of the Clones
69 Return of the Jedi
70 The Phantom Menace
71 The Phantom Menace , Revenge of the Sith
72 The Phantom Menace , Revenge of the Sith
73 The Phantom Menace
74 The Phantom Menace  , Attack of the Clones
75 Attack of the Clones
76 Attack of the Clones
77 Attack of the Clones
78 Attack of the Clones, Revenge of the Sith
79 Attack of the Clones
80 Attack of the Clones
81 Attack of the Clones, Revenge of the Sith
82 Attack of the Clones
83 The Force Awakens
84 The Force Awakens
85 The Force Awakens
86 The Force Awakens
87 The Force Awakens
   vehicles
1
2
3
4
5
6
7
8
9
10
11 Imperial Speeder Bike
12
13
14
15 Koro-2 Exodrive airspeeder
16
17
18
19
20
21
22
23
24
25 Snowspeeder          , Imperial Speeder Bike
26 Tribubble bongo
27 Snowspeeder
28
29
30
⋮  ⋮
58 Tsmeu-6 personal wheel bike
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
   starships
1
2
3
4
5
6
7  Naboo fighter      , H-type Nubian yacht, Naboo star skiff
8
9
10
11
12
13
14
15
16
17
18
19
20 Millennium Falcon
21
22
23
24
25 X-wing          , Imperial shuttle
26 Jedi starfighter        , Trade Federation cruiser, Naboo star skiff        , Jedi Interceptor        , Belbullab-22 starfighter
27 X-wing
28 Slave 1
29 Millennium Falcon
30
⋮  ⋮
58 Belbullab-22 starfighter
59
60
61
62 A-wing
63
64
65 Naboo Royal Starship
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85 X-wing
86
87

`-` group-wise statistic / select

> 그룹별 통계량

In [35]:
e = starwars %>% group_by(species) %>% summarise(
    n = n(), mass = mean(mass, na.rm = TRUE)) %>% filter(n > 1, mass > 60)
e

  species  n  mass
1 Droid     6  69.75
2 Gungan    3  74.00
3 Human    35  81.31
4 Kaminoan  2  88.00
5 Wookiee   2 124.00
6 Zabrak    2  80.00
7 NA        4  81.00

> `group_by()` : 판다스 groupby()라고 보면 됨.
>
> `summarse()` : 연산을 수행

`-` 중복의 처리

In [38]:
df2 <- starwars %>% distinct(height, .keep_all = TRUE)  ## 중복이 있으면 제일 위의 것
df2 |> head()

  name           height mass hair_color  skin_color  eye_color birth_year
1 Luke Skywalker 172     77  blond       fair        blue       19.0
2 C-3PO          167     75  NA          gold        yellow    112.0
3 R2-D2           96     32  NA          white, blue red        33.0
4 Darth Vader    202    136  none        white       yellow     41.9
5 Leia Organa    150     49  brown       light       brown      19.0
6 Owen Lars      178    120  brown, grey light       blue       52.0
  sex    gender    homeworld species
1 male   masculine Tatooine  Human
2 none   masculine Tatooine  Droid
3 none   masculine Naboo     Droid
4 male   masculine Tatooine  Human
5 female feminine  Alderaan  Human
6 male   masculine Tatooine  Human
  films
1 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith    , The Force Awakens
2 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
3 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith    , The Force Awakens
4 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith
5 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith    , The Force Awakens
6 A New Hope          , Attack of the Clones, Revenge of the Sith
  vehicles
1 Snowspeeder          , Imperial Speeder Bike
2
3
4
5 Imperial Speeder Bike
6
  starships
1 X-wing          , Imperial shuttle
2
3
4 TIE Advanced x1
5
6

In [40]:
df3 <- starwars %>% slice(2:40)
df3 |> head()

  name               height mass hair_color  skin_color  eye_color birth_year
1 C-3PO              167     75  NA          gold        yellow    112.0
2 R2-D2               96     32  NA          white, blue red        33.0
3 Darth Vader        202    136  none        white       yellow     41.9
4 Leia Organa        150     49  brown       light       brown      19.0
5 Owen Lars          178    120  brown, grey light       blue       52.0
6 Beru Whitesun Lars 165     75  brown       light       blue       47.0
  sex    gender    homeworld species
1 none   masculine Tatooine  Droid
2 none   masculine Naboo     Droid
3 male   masculine Tatooine  Human
4 female feminine  Alderaan  Human
5 male   masculine Tatooine  Human
6 female feminine  Tatooine  Human
  films
1 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith
2 A New Hope             , The Empire Strikes Back, Return of the Jedi     , The Phantom Menace     , Attack of the Clones   , Revenge of the Sith    , The Force Awakens
3 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith
4 A New Hope             , The Empire Strikes Back, Return of the Jedi     , Revenge of the Sith    , The Force Awakens
5 A New Hope          , Attack of the Clones, Revenge of the Sith
6 A New Hope          , Attack of the Clones, Revenge of the Sith
  vehicles              starships
1
2
3                       TIE Advanced x1
4 Imperial Speeder Bike
5
6

In [41]:
print(df3, n = 39, width = Inf)

# A tibble: 39 × 14
   name                  height   mass hair_color    skin_color       eye_color
   <chr>                  <int>  <dbl> <chr>         <chr>            <chr>
 1 C-3PO                    167   75   NA            gold             yellow
 2 R2-D2                     96   32   NA            white, blue      red
 3 Darth Vader              202  136   none          white            yellow
 4 Leia Organa              150   49   brown         light            brown
 5 Owen Lars                178  120   brown, grey   light            blue
 6 Beru Whitesun Lars       165   75   brown         light            blue
 7 R5-D4                     97   32   NA            white, red       red
 8 Biggs Darklighter        183   84   black         light            brown
 9 Obi-Wan Kenobi           182   77   auburn, white fair             blue-gray
10 Anakin Skywalker         188   84   blond         fair             blue
11 Wilhuff Tarkin           180   NA   auburn, grey  fair             blue
12 Chewbacca                228  112   brown         unknown          blue
13 Han Solo                 180   80   brown         fair             brown
14 Greedo                   173   74   NA            green            black
15 Jabba Desilijic Tiure    175 1358   NA            green-tan, brown orange
16 Wedge Antilles           170   77   brown         fair             hazel
17 Jek Tono Porkins         180  110   brown         fair             blue
18 Yoda                      66   17   white         green            brown
19 Palpatine                170   75   grey          pale             yellow
20 Boba Fett                183   78.2 black         fair             brown
21 IG-88                    200  140   none          metal            red
22 Bossk                    190  113   none          green            red
23 Lando Calrissian         177   79   black         dark             brown
24 Lobot                    175   79   none          light            blue
25 Ackbar                   180   83   none          brown mottle     orange
26 Mon Mothma               150   NA   auburn        fair             blue
27 Arvel Crynyd              NA   NA   brown         fair             brown
28 Wicket Systri Warrick     88   20   brown         brown            brown
29 Nien Nunb                160   68   none          grey             black
30 Qui-Gon Jinn             193   89   brown         fair             blue
31 Nute Gunray              191   90   none          mottled green    red
32 Finis Valorum            170   NA   blond         fair             blue
33 Padmé Amidala            185   45   brown         light            brown
34 Jar Jar Binks            196   66   none          orange           orange
35 Roos Tarpals             224   82   none          grey             orange
36 Rugor Nass               206   NA   none          green            orange
37 Ric Olié                 183   NA   brown         fair             blue
38 Watto                    137   NA   black         blue, grey       yellow
39 Sebulba                  112   40   none          grey, red        orange
   birth_year sex            gender    homeworld      species        films
        <dbl> <chr>          <chr>     <chr>          <chr>          <list>
 1      112   none           masculine Tatooine       Droid          <chr [6]>
 2       33   none           masculine Naboo          Droid          <chr [7]>
 3       41.9 male           masculine Tatooine       Human          <chr [4]>
 4       19   female         feminine  Alderaan       Human          <chr [5]>
 5       52   male           masculine Tatooine       Human          <chr [3]>
 6       47   female         feminine  Tatooine       Human          <chr [3]>
 7       NA   none           masculine Tatooine       Droid          <chr [1]>
 8       24   male           masculine Tatooine       Human          <chr [1]>
 9       57   male           masculine Stewjon        Human          <chr [6]>
10       41.9 male           masculine Tatooine       Human          <chr [3]>
11       64   male           masculine Eriadu         Human          <chr [2]>
12      200   male           masculine Kashyyyk       Wookiee        <chr [5]>
13       29   male           masculine Corellia       Human          <chr [4]>
14       44   male           masculine Rodia          Rodian         <chr [1]>
15      600   hermaphroditic masculine Nal Hutta      Hutt           <chr [3]>
16       21   male           masculine Corellia       Human          <chr [3]>
17       NA   NA             NA        Bestine IV     NA             <chr [1]>
18      896   male           masculine NA             Yoda's species <chr [5]>
19       82   male           masculine Naboo          Human          <chr [5]>
20       31.5 male           masculine Kamino         Human          <chr [3]>
21       15   none           masculine NA             Droid          <chr [1]>
22       53   male           masculine Trandosha      Trandoshan     <chr [1]>
23       31   male           masculine Socorro        Human          <chr [2]>
24       37   male           masculine Bespin         Human          <chr [1]>
25       41   male           masculine Mon Cala       Mon Calamari   <chr [2]>
26       48   female         feminine  Chandrila      Human          <chr [1]>
27       NA   male           masculine NA             Human          <chr [1]>
28        8   male           masculine Endor          Ewok           <chr [1]>
29       NA   male           masculine Sullust        Sullustan      <chr [1]>
30       92   male           masculine NA             Human          <chr [1]>
31       NA   male           masculine Cato Neimoidia Neimodian      <chr [3]>
32       91   male           masculine Coruscant      Human          <chr [1]>
33       46   female         feminine  Naboo          Human          <chr [3]>
34       52   male           masculine Naboo          Gungan         <chr [2]>
35       NA   male           masculine Naboo          Gungan         <chr [1]>
36       NA   male           masculine Naboo          Gungan         <chr [1]>
37       NA   male           masculine Naboo          Human          <chr [1]>
38       NA   male           masculine Toydaria       Toydarian      <chr [2]>
39       NA   male           masculine Malastare      Dug            <chr [1]>
   vehicles  starships
   <list>    <list>
 1 <chr [0]> <chr [0]>
 2 <chr [0]> <chr [0]>
 3 <chr [0]> <chr [1]>
 4 <chr [1]> <chr [0]>
 5 <chr [0]> <chr [0]>
 6 <chr [0]> <chr [0]>
 7 <chr [0]> <chr [0]>
 8 <chr [0]> <chr [1]>
 9 <chr [1]> <chr [5]>
10 <chr [2]> <chr [3]>
11 <chr [0]> <chr [0]>
12 <chr [1]> <chr [2]>
13 <chr [0]> <chr [2]>
14 <chr [0]> <chr [0]>
15 <chr [0]> <chr [0]>
16 <chr [1]> <chr [1]>
17 <chr [0]> <chr [1]>
18 <chr [0]> <chr [0]>
19 <chr [0]> <chr [0]>
20 <chr [0]> <chr [1]>
21 <chr [0]> <chr [0]>
22 <chr [0]> <chr [0]>
23 <chr [0]> <chr [1]>
24 <chr [0]> <chr [0]>
25 <chr [0]> <chr [0]>
26 <chr [0]> <chr [0]>
27 <chr [0]> <chr [1]>
28 <chr [0]> <chr [0]>
29 <chr [0]> <chr [1]>
30 <chr [1]> <chr [0]>
31 <chr [0]> <chr [0]>
32 <chr [0]> <chr [0]>
33 <chr [0]> <chr [3]>
34 <chr [0]> <chr [0]>
35 <chr [0]> <chr [0]>
36 <chr [0]> <chr [0]>
37 <chr [0]> <chr [1]>
38 <chr [0]> <chr [0]>
39 <chr [0]> <chr [0]>

In [44]:
c = select(starwars, contains("e"))  ## project
c |> head()

  name           height eye_color birth_year sex    gender    homeworld species
1 Luke Skywalker 172    blue       19.0      male   masculine Tatooine  Human
2 C-3PO          167    yellow    112.0      none   masculine Tatooine  Droid
3 R2-D2           96    red        33.0      none   masculine Naboo     Droid
4 Darth Vader    202    yellow     41.9      male   masculine Tatooine  Human
5 Leia Organa    150    brown      19.0      female feminine  Alderaan  Human
6 Owen Lars      178    blue       52.0      male   masculine Tatooine  Human
  vehicles
1 Snowspeeder          , Imperial Speeder Bike
2
3
4
5 Imperial Speeder Bike
6

`-` Join

In [46]:
set.seed(222)
d1 = data.frame(id = rep(1:10), c = rpois(10*1, 2))
d2 = data.frame(id = 2:11, d = rpois(10,4))

In [47]:
inner_join(d1, d2, by = "id")

  id c d
1  2 0 3
2  3 2 1
3  4 0 2
4  5 4 5
5  6 5 7
6  7 1 1
7  8 2 5
8  9 2 1
9 10 1 2

In [48]:
full_join(d1, d2, by = "id")

   id c  d
1   1  4 NA
2   2  0  3
3   3  2  1
4   4  0  2
5   5  4  5
6   6  5  7
7   7  1  1
8   8  2  5
9   9  2  1
10 10  1  2
11 11 NA  2

In [52]:
right_join(d1, d2, by = "id")

   id c  d
1   2  0 3
2   3  2 1
3   4  0 2
4   5  4 5
5   6  5 7
6   7  1 1
7   8  2 5
8   9  2 1
9  10  1 2
10 11 NA 2

In [53]:
left_join(d1, d2, by = "id")

   id c d
1   1 4 NA
2   2 0  3
3   3 2  1
4   4 0  2
5   5 4  5
6   6 5  7
7   7 1  1
8   8 2  5
9   9 2  1
10 10 1  2

In [51]:
merge(d1, d2, by = "id", all.x = T, all.y = T)

   id c  d
1   1  4 NA
2   2  0  3
3   3  2  1
4   4  0  2
5   5  4  5
6   6  5  7
7   7  1  1
8   8  2  5
9   9  2  1
10 10  1  2
11 11 NA  2

> `pd.merge(df1, df2, by = "id", how = "right, left, ...")`

`-` 일반 집합 연산자 : union, intersection, setdiff

In [55]:
set.seed(222)
d1 = data.frame(id = rep(1:5), c = rpois(5*1,2))
d2 = data.frame(id = c(1,2,4,5,6), c = c(d1[1:2, 2], rpois(3,4)))

In [56]:
union(d1, d2)

  id c
1 1  4
2 2  0
3 3  2
4 4  0
5 5  4
6 4  8
7 5  3
8 6  3

> 다르기만 하면 다 더해짐

In [57]:
intersect(d1, d2)

  id c
1 1  4
2 2  0

In [58]:
setdiff(d1, d2)

  id c
1 3  2
2 4  0
3 5  4

In [59]:
setdiff(d2, d1)

  id c
1 4  8
2 5  3
3 6  3

`-` cartesian product

In [68]:
x = rnorm(100); v = rnorm(100); y = rnorm(100); rbinom(100, 1, 0.5)

d1 <- data.frame(x=x, v=v, c=v)
expand(data.frame(y=y, z=z), d1, nesting(y, z))  ## 앞의 것들을 고정시키고 y_z를 바꾸는 식으로 변경

  [1] 0 0 0 0 1 0 1 1 0 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 0 1 1 1 0 1 0 0 0 1 0 0 1
 [38] 0 0 1 1 1 1 1 0 1 1 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 0 0 0 1
 [75] 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 0

ERROR: Error in expand(data.frame(y = y, z = z), d1, nesting(y, z)): could not find function "expand"